-- CREATE USER "taskdev" WITH PASSWORD '8Br99LU%';
-- CREATE DATABASE "taskdb" OWNER "taskdev";
GRANT ALL PRIVILEGES ON DATABASE "taskdb" TO "taskdev";

-- USE "taskdb"

CREATE TABLE tasks (
  id VARCHAR(255) PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  status VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdBy VARCHAR(255) NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedBy VARCHAR(255) NOT NULL
);
