/**
 * Task Management API
 * API for managing tasks with different states
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ReportsReportSummary200Response {
  totalTasks?: number;
  toDoTasks?: number;
  inProgressTasks?: number;
  doneTasks?: number;
  archivedTasks?: number;
}
