/**
 * Task Management API
 * API for managing tasks with different states
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Basic response model used as the base of all responses for HTTP.
 */
export interface ResponseModel {
  /**
   * Operation over client was successful.
   */
  success: boolean;
  /**
   * Human-readable description of the status message.
   */
  message: string;
  /**
   * Information identifying when a certain event occurred, usually giving date and time of day, sometimes accurate to a small fraction of a second.
   */
  timestamp: string;
}
