/**
 * Task Management API
 * API for managing tasks with different states
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TaskUpdate {
  title?: string;
  description?: string;
  status?: TaskUpdate.StatusEnum;
}
export namespace TaskUpdate {
  export type StatusEnum = 'To do' | 'In Progress' | 'Done' | 'Archived';
  export const StatusEnum = {
    ToDo: 'To do' as StatusEnum,
    InProgress: 'In Progress' as StatusEnum,
    Done: 'Done' as StatusEnum,
    Archived: 'Archived' as StatusEnum,
  };
}
