/**
 * Task Management API
 * API for managing tasks with different states
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Task {
    id: string;
    title: string;
    description?: string;
    status: Task.StatusEnum;
    createdAt: string;
    createdBy: string;
    updatedAt: string;
    updatedBy: string;
}
export namespace Task {
    export type StatusEnum = 'To do' | 'In Progress' | 'Done' | 'Archived';
    export const StatusEnum = {
        ToDo: 'To do' as StatusEnum,
        InProgress: 'In Progress' as StatusEnum,
        Done: 'Done' as StatusEnum,
        Archived: 'Archived' as StatusEnum
    };
}


